#!/bin/sh

os=""
arch=""

case "$(uname)" in
  Linux)
    os="linux"

    case "$(uname -m)" in
      x86_64)
        arch="amd64"
        ;;
      aarch64)
        arch="arm64"
        ;;
      armv7l)
        arch="armv7"
        ;;
      *)
        echo "Error: For now, prebuilt binaries are only available for x86_64, aarch64, and armv7l."
        exit 1
        ;;
    esac
    ;;
  *)
    echo "Error: For now, prebuilt binaries are only available for Linux"
    exit 1
    ;;
esac

TMP_FILE=$(mktemp /tmp/mup.XXXXXX)

echo "Downloading GitHub releases: https://github.com/aziis98/mup/releases/latest/download/mup-$os-$arch"
wget -q --show-progress -O "$TMP_FILE" "https://github.com/aziis98/mup/releases/latest/download/mup-$os-$arch"

if [ $? -ne 0 ]; then
  echo "Error: Failed to download mup."
  exit 1
fi

echo "Download completed."

chmod +x "$TMP_FILE"

mkdir -p "$HOME/.local/bin"

echo "Moving mup to $HOME/.local/bin..."
mv "$TMP_FILE" "$HOME/.local/bin/mup"

if ! echo "$PATH" | grep -q "$HOME/.local/bin"; then
  echo "Warning: $HOME/.local/bin is not in your PATH. You may need to add it."
  echo "Add the following line to your shell configuration file:"
  echo
  echo '  export PATH="$HOME/.local/bin:$PATH"'
  echo
fi

echo "Installation completed successfully."
