#!/bin/sh

TMP_FILE=$(mktemp /tmp/mup.XXXXXX)

echo "Downloading latest version from GitHub releases..."
wget -q --show-progress -O "$TMP_FILE" https://github.com/aziis98/mup/releases/latest/download/mup

if [ $? -ne 0 ]; then
  echo "Error: Failed to download mup."
  exit 1
fi

echo "Download completed."

echo "Setting executable permissions on mup..."
chmod +x "$TMP_FILE"

echo "Ensuring $HOME/.local/bin exists..."
mkdir -p "$HOME/.local/bin"

echo "Moving mup to $HOME/.local/bin..."
mv "$TMP_FILE" "$HOME/.local/bin/mup"

if ! echo "$PATH" | grep -q "$HOME/.local/bin"; then
  echo "Warning: $HOME/.local/bin is not in your PATH. You may need to add it to your PATH."
fi

echo "Installation completed successfully."
